import {
  BACKEND_DEVELOPMENT_ROUTE,
  BUSINESS_SOLUTIONS_ROUTE,
  FRONTEND_DEVELOPMENT_ROUTE,
  MOBILE_APP_DEVELOPMENT_ROUTE,
  SOFTWARE_DEVELOPMENT_ROUTE,
  PRODUCT_ENGINEERING_ROUTE,
  UI_UX_DESIGN_ROUTE,
  WEB_DEVELOPMENT_ROUTE,
} from "@/lib/design-and-development/service-routes";

/** Mega-menu Design & Development item label → route */
export const DESIGN_ITEM_HREFS: Record<string, string> = {
  "Software Development": SOFTWARE_DEVELOPMENT_ROUTE,
  "Custom Software Development": SOFTWARE_DEVELOPMENT_ROUTE,
  "Full Stack Web Development": SOFTWARE_DEVELOPMENT_ROUTE,
  "Enterprise Application Development": SOFTWARE_DEVELOPMENT_ROUTE,
  "SaaS Product Development": SOFTWARE_DEVELOPMENT_ROUTE,
  "Startup MVP Development": SOFTWARE_DEVELOPMENT_ROUTE,
  "API Development & Integration": SOFTWARE_DEVELOPMENT_ROUTE,
  "Cloud-Based Applications": SOFTWARE_DEVELOPMENT_ROUTE,
  "Web Development": WEB_DEVELOPMENT_ROUTE,
  "Corporate Websites": WEB_DEVELOPMENT_ROUTE,
  "Business Websites": WEB_DEVELOPMENT_ROUTE,
  "Portfolio Websites": WEB_DEVELOPMENT_ROUTE,
  "Landing Pages": WEB_DEVELOPMENT_ROUTE,
  "Admin Dashboards": WEB_DEVELOPMENT_ROUTE,
  "CRM & ERP Systems": WEB_DEVELOPMENT_ROUTE,
  "Analytics Platforms": WEB_DEVELOPMENT_ROUTE,
  "E-commerce Platforms": WEB_DEVELOPMENT_ROUTE,
  "Booking & Management Systems": WEB_DEVELOPMENT_ROUTE,
  "Mobile App Development": MOBILE_APP_DEVELOPMENT_ROUTE,
  "Android App Development": MOBILE_APP_DEVELOPMENT_ROUTE,
  "React Native Applications": MOBILE_APP_DEVELOPMENT_ROUTE,
  "Cross-Platform Mobile Apps": MOBILE_APP_DEVELOPMENT_ROUTE,
  "Business Mobile Applications": MOBILE_APP_DEVELOPMENT_ROUTE,
  "Real-Time Applications": MOBILE_APP_DEVELOPMENT_ROUTE,
  "Frontend Development": FRONTEND_DEVELOPMENT_ROUTE,
  "React.js Development": FRONTEND_DEVELOPMENT_ROUTE,
  "TypeScript Applications": FRONTEND_DEVELOPMENT_ROUTE,
  "Modern UI Development": FRONTEND_DEVELOPMENT_ROUTE,
  "Responsive Web Interfaces": FRONTEND_DEVELOPMENT_ROUTE,
  "Interactive User Experiences": FRONTEND_DEVELOPMENT_ROUTE,
  "Tailwind CSS Development": FRONTEND_DEVELOPMENT_ROUTE,
  "Backend Development": BACKEND_DEVELOPMENT_ROUTE,
  "Node.js & Express.js Development": BACKEND_DEVELOPMENT_ROUTE,
  "REST API Development": BACKEND_DEVELOPMENT_ROUTE,
  "Authentication Systems": BACKEND_DEVELOPMENT_ROUTE,
  "Database Architecture": BACKEND_DEVELOPMENT_ROUTE,
  "Firebase Integration": BACKEND_DEVELOPMENT_ROUTE,
  "Scalable Backend Systems": BACKEND_DEVELOPMENT_ROUTE,
  "UI/UX Design": UI_UX_DESIGN_ROUTE,
  "Website UI Design": UI_UX_DESIGN_ROUTE,
  "Mobile App UI Design": UI_UX_DESIGN_ROUTE,
  "Dashboard Design": UI_UX_DESIGN_ROUTE,
  "SaaS Product Design": UI_UX_DESIGN_ROUTE,
  "Wireframing & Prototyping": UI_UX_DESIGN_ROUTE,
  "Responsive UI/UX": UI_UX_DESIGN_ROUTE,
  "Premium Modern Interfaces": UI_UX_DESIGN_ROUTE,
  "Product Engineering": PRODUCT_ENGINEERING_ROUTE,
  "End-to-End Product Development": PRODUCT_ENGINEERING_ROUTE,
  "Product Planning & Architecture": PRODUCT_ENGINEERING_ROUTE,
  "Feature Development": PRODUCT_ENGINEERING_ROUTE,
  "Performance Optimization": PRODUCT_ENGINEERING_ROUTE,
  "System Integration": PRODUCT_ENGINEERING_ROUTE,
  "Product Maintenance & Support": PRODUCT_ENGINEERING_ROUTE,
  "Business Solutions": BUSINESS_SOLUTIONS_ROUTE,
  "Inventory Management Systems": BUSINESS_SOLUTIONS_ROUTE,
  "Employee Management Systems": BUSINESS_SOLUTIONS_ROUTE,
  "Customer Management Platforms": BUSINESS_SOLUTIONS_ROUTE,
  "Billing Systems": BUSINESS_SOLUTIONS_ROUTE,
  "Workflow Automation": BUSINESS_SOLUTIONS_ROUTE,
  "Reporting & Analytics Systems": BUSINESS_SOLUTIONS_ROUTE,
};
