export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ?? "https://brandmarketing.digital";

/** Public, indexable routes (exclude redirect-only pages). */
export const PUBLIC_ROUTES: string[] = [
  "/",
  "/about",
  "/contact",
  "/careers",
  "/branding",
  "/services",
  "/social-media",
  "/seo",
  "/seo/local",
  "/seo/technical",
  "/seo/franchise",
  "/seo/ai",
  "/seo/aiseo",
  "/digital-marketing-services",
  "/digital-marketing-services/ppc",
  "/digital-marketing-services/link-building",
  "/digital-marketing-services/online-marketplace-marketing",
  "/digital-marketing",
  "/digital-marketing/strategy",
  "/digital-marketing/development",
  "/digital-marketing/ecommerce",
  "/digital-marketing/franchise",
  "/digital-marketing/enterprise",
  "/design-and-development",
  "/design-and-development/software-development",
  "/design-and-development/web-development",
  "/design-and-development/mobile-app-development",
  "/design-and-development/frontend-development",
  "/design-and-development/backend-development",
  "/design-and-development/ui-ux-design",
  "/design-and-development/product-engineering",
  "/design-and-development/business-solutions",
  "/design-and-development/development-process",
];
